name = "apparel-is"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = "./.svelte-kit/cloudflare"

[vars]
# Set these in Cloudflare dashboard for production.
PRINTIFY_STORE_ID = ""
ADMIN_TOKEN = ""
ADMIN_API_TOKEN = ""

# Printify token should be a secret in production:
# wrangler secret put PRINTIFY_API_TOKEN

# Admin API token should be a secret in production (if you want to call /api/admin/* programmatically):
# wrangler secret put ADMIN_API_TOKEN
